/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "EZI2C_1.h"
#include "EZI2C_1_PINS.h"
#include "EZI2C_1_PVT.h"
#include "EZI2C_1_EZI2C.h"
#include "EZI2C_1_EZI2C_PVT.h"
#include "EZI2C_1_BOOT.h"
#include "EZI2C_1_SCBCLK.h"
#include "EZI2C_1_sda.h"
#include "EZI2C_1_sda_aliases.h"
#include "EZI2C_1_scl.h"
#include "EZI2C_1_scl_aliases.h"
#include "EZI2C_1_SCB_IRQ.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

