/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "USBUART.h"
#include "USBUART_audio.h"
#include "USBUART_cdc.h"
#include "USBUART_hid.h"
#include "USBUART_midi.h"
#include "USBUART_pvt.h"
#include "USBUART_cydmac.h"
#include "USBUART_msc.h"
#include "ADC_DelSig_1.h"
#include "TIA_1.h"
#include "VDAC_Vgs.h"
#include "Pin_SolutionGate_aliases.h"
#include "Pin_SolutionGate.h"
#include "VDAC_Vds.h"
#include "Pin_Vds_aliases.h"
#include "Pin_Vds.h"
#include "Pin_Vss_aliases.h"
#include "Pin_Vss.h"
#include "VDAC_Ref.h"
#include "SDA_1_aliases.h"
#include "SDA_1.h"
#include "SCL_1_aliases.h"
#include "SCL_1.h"
#include "I2C_1.h"
#include "I2C_1_PVT.h"
#include "UART_1.h"
#include "CommunicationTimer.h"
#include "CommunicationInterrupt.h"
#include "ADC_SAR_1.h"
#include "Pin_I12_aliases.h"
#include "Pin_I12.h"
#include "Pin_I11_aliases.h"
#include "Pin_I11.h"
#include "ADC_SAR_2.h"
#include "DieTemp.h"
#include "Pin_I1_GND_aliases.h"
#include "Pin_I1_GND.h"
#include "Pin_BackGate_aliases.h"
#include "Pin_BackGate.h"
#include "Pin_LocalGates_aliases.h"
#include "Pin_LocalGates.h"
#include "USBUART_Dm_aliases.h"
#include "USBUART_Dm.h"
#include "USBUART_Dp_aliases.h"
#include "USBUART_Dp.h"
#include "ADC_DelSig_1_Ext_CP_Clk.h"
#include "ADC_DelSig_1_IRQ.h"
#include "ADC_DelSig_1_theACLK.h"
#include "I2C_1_IntClock.h"
#include "UART_1_IntClock.h"
#include "ADC_SAR_1_IRQ.h"
#include "ADC_SAR_1_theACLK.h"
#include "ADC_SAR_2_IRQ.h"
#include "ADC_SAR_2_theACLK.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

